name
validationResults {
  level
  message
}
allGeneMutations {
  gene { name }
  mutations {
    consensus
    position
    AAs
    isInsertion
    isDeletion
    isUnusual
    hasStop
    text
  }
}
